//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace LateralMenus.ProductManager {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://manager.entity.upreal", ConfigurationName="ProductManager.ProductManagerPortType")]
    public interface ProductManagerPortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:getProduct", ReplyAction="urn:getProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetProduct(LateralMenus.ProductManager.getProductRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.ProductManager.getProductResponse EndgetProduct(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:getProductByBrand", ReplyAction="urn:getProductByBrandResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetProductByBrand(LateralMenus.ProductManager.getProductByBrandRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.ProductManager.getProductByBrandResponse EndgetProductByBrand(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:updateProduct", ReplyAction="urn:updateProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginupdateProduct(LateralMenus.ProductManager.updateProductRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.ProductManager.updateProductResponse EndupdateProduct(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:registerProduct", ReplyAction="urn:registerProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginregisterProduct(LateralMenus.ProductManager.registerProductRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.ProductManager.registerProductResponse EndregisterProduct(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:getProductByEAN", ReplyAction="urn:getProductByEANResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetProductByEAN(LateralMenus.ProductManager.getProductByEANRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.ProductManager.getProductByEANResponse EndgetProductByEAN(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:getProductByName", ReplyAction="urn:getProductByNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetProductByName(LateralMenus.ProductManager.getProductByNameRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.ProductManager.getProductByNameResponse EndgetProductByName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:deleteProduct", ReplyAction="urn:deleteProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegindeleteProduct(int id, System.AsyncCallback callback, object asyncState);
        
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool EnddeleteProduct(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:getProductInfo", ReplyAction="urn:getProductInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetProductInfo(LateralMenus.ProductManager.getProductInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.ProductManager.getProductInfoResponse EndgetProductInfo(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pojo.entity.upreal/xsd")]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string brandField;
        
        private int eanField;
        
        private bool eanFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string pictureField;
        
        private System.Nullable<System.DateTime> upload_dateField;
        
        private bool upload_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ean {
            get {
                return this.eanField;
            }
            set {
                this.eanField = value;
                this.RaisePropertyChanged("ean");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eanSpecified {
            get {
                return this.eanFieldSpecified;
            }
            set {
                this.eanFieldSpecified = value;
                this.RaisePropertyChanged("eanSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
                this.RaisePropertyChanged("picture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> upload_date {
            get {
                return this.upload_dateField;
            }
            set {
                this.upload_dateField = value;
                this.RaisePropertyChanged("upload_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool upload_dateSpecified {
            get {
                return this.upload_dateFieldSpecified;
            }
            set {
                this.upload_dateFieldSpecified = value;
                this.RaisePropertyChanged("upload_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProduct", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string keyword;
        
        public getProductRequest() {
        }
        
        public getProductRequest(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public LateralMenus.ProductManager.Product[] @return;
        
        public getProductResponse() {
        }
        
        public getProductResponse(LateralMenus.ProductManager.Product[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductByBrand", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getProductByBrandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string brand;
        
        public getProductByBrandRequest() {
        }
        
        public getProductByBrandRequest(string brand) {
            this.brand = brand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductByBrandResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getProductByBrandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public LateralMenus.ProductManager.Product[] @return;
        
        public getProductByBrandResponse() {
        }
        
        public getProductByBrandResponse(LateralMenus.ProductManager.Product[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateProduct", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class updateProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=2)]
        public int ean;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string picture;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string brand;
        
        public updateProductRequest() {
        }
        
        public updateProductRequest(int id, string name, int ean, string picture, string brand) {
            this.id = id;
            this.name = name;
            this.ean = ean;
            this.picture = picture;
            this.brand = brand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateProductResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class updateProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        public bool @return;
        
        public updateProductResponse() {
        }
        
        public updateProductResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerProduct", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class registerProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=1)]
        public int ean;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string picture;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string brand;
        
        public registerProductRequest() {
        }
        
        public registerProductRequest(string name, int ean, string picture, string brand) {
            this.name = name;
            this.ean = ean;
            this.picture = picture;
            this.brand = brand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerProductResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class registerProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        public int @return;
        
        public registerProductResponse() {
        }
        
        public registerProductResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductByEAN", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getProductByEANRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        public int ean;
        
        public getProductByEANRequest() {
        }
        
        public getProductByEANRequest(int ean) {
            this.ean = ean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductByEANResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getProductByEANResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LateralMenus.ProductManager.Product @return;
        
        public getProductByEANResponse() {
        }
        
        public getProductByEANResponse(LateralMenus.ProductManager.Product @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductByName", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getProductByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name;
        
        public getProductByNameRequest() {
        }
        
        public getProductByNameRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductByNameResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getProductByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public LateralMenus.ProductManager.Product[] @return;
        
        public getProductByNameResponse() {
        }
        
        public getProductByNameResponse(LateralMenus.ProductManager.Product[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductInfo", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getProductInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        public int id;
        
        public getProductInfoRequest() {
        }
        
        public getProductInfoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductInfoResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getProductInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LateralMenus.ProductManager.Product @return;
        
        public getProductInfoResponse() {
        }
        
        public getProductInfoResponse(LateralMenus.ProductManager.Product @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductManagerPortTypeChannel : LateralMenus.ProductManager.ProductManagerPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LateralMenus.ProductManager.Product[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LateralMenus.ProductManager.Product[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getProductByBrandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getProductByBrandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LateralMenus.ProductManager.Product[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LateralMenus.ProductManager.Product[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class updateProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public updateProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class registerProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public registerProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getProductByEANCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getProductByEANCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LateralMenus.ProductManager.Product Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LateralMenus.ProductManager.Product)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getProductByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getProductByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LateralMenus.ProductManager.Product[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LateralMenus.ProductManager.Product[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class deleteProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public deleteProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getProductInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getProductInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LateralMenus.ProductManager.Product Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LateralMenus.ProductManager.Product)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductManagerPortTypeClient : System.ServiceModel.ClientBase<LateralMenus.ProductManager.ProductManagerPortType>, LateralMenus.ProductManager.ProductManagerPortType {
        
        private BeginOperationDelegate onBegingetProductDelegate;
        
        private EndOperationDelegate onEndgetProductDelegate;
        
        private System.Threading.SendOrPostCallback ongetProductCompletedDelegate;
        
        private BeginOperationDelegate onBegingetProductByBrandDelegate;
        
        private EndOperationDelegate onEndgetProductByBrandDelegate;
        
        private System.Threading.SendOrPostCallback ongetProductByBrandCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdateProductDelegate;
        
        private EndOperationDelegate onEndupdateProductDelegate;
        
        private System.Threading.SendOrPostCallback onupdateProductCompletedDelegate;
        
        private BeginOperationDelegate onBeginregisterProductDelegate;
        
        private EndOperationDelegate onEndregisterProductDelegate;
        
        private System.Threading.SendOrPostCallback onregisterProductCompletedDelegate;
        
        private BeginOperationDelegate onBegingetProductByEANDelegate;
        
        private EndOperationDelegate onEndgetProductByEANDelegate;
        
        private System.Threading.SendOrPostCallback ongetProductByEANCompletedDelegate;
        
        private BeginOperationDelegate onBegingetProductByNameDelegate;
        
        private EndOperationDelegate onEndgetProductByNameDelegate;
        
        private System.Threading.SendOrPostCallback ongetProductByNameCompletedDelegate;
        
        private BeginOperationDelegate onBegindeleteProductDelegate;
        
        private EndOperationDelegate onEnddeleteProductDelegate;
        
        private System.Threading.SendOrPostCallback ondeleteProductCompletedDelegate;
        
        private BeginOperationDelegate onBegingetProductInfoDelegate;
        
        private EndOperationDelegate onEndgetProductInfoDelegate;
        
        private System.Threading.SendOrPostCallback ongetProductInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ProductManagerPortTypeClient() {
        }
        
        public ProductManagerPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductManagerPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductManagerPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductManagerPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getProductCompletedEventArgs> getProductCompleted;
        
        public event System.EventHandler<getProductByBrandCompletedEventArgs> getProductByBrandCompleted;
        
        public event System.EventHandler<updateProductCompletedEventArgs> updateProductCompleted;
        
        public event System.EventHandler<registerProductCompletedEventArgs> registerProductCompleted;
        
        public event System.EventHandler<getProductByEANCompletedEventArgs> getProductByEANCompleted;
        
        public event System.EventHandler<getProductByNameCompletedEventArgs> getProductByNameCompleted;
        
        public event System.EventHandler<deleteProductCompletedEventArgs> deleteProductCompleted;
        
        public event System.EventHandler<getProductInfoCompletedEventArgs> getProductInfoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.ProductManager.ProductManagerPortType.BegingetProduct(LateralMenus.ProductManager.getProductRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetProduct(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetProduct(string keyword, System.AsyncCallback callback, object asyncState) {
            LateralMenus.ProductManager.getProductRequest inValue = new LateralMenus.ProductManager.getProductRequest();
            inValue.keyword = keyword;
            return ((LateralMenus.ProductManager.ProductManagerPortType)(this)).BegingetProduct(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.ProductManager.getProductResponse LateralMenus.ProductManager.ProductManagerPortType.EndgetProduct(System.IAsyncResult result) {
            return base.Channel.EndgetProduct(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private LateralMenus.ProductManager.Product[] EndgetProduct(System.IAsyncResult result) {
            LateralMenus.ProductManager.getProductResponse retVal = ((LateralMenus.ProductManager.ProductManagerPortType)(this)).EndgetProduct(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetProduct(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string keyword = ((string)(inValues[0]));
            return this.BegingetProduct(keyword, callback, asyncState);
        }
        
        private object[] OnEndgetProduct(System.IAsyncResult result) {
            LateralMenus.ProductManager.Product[] retVal = this.EndgetProduct(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetProductCompleted(object state) {
            if ((this.getProductCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getProductCompleted(this, new getProductCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getProductAsync(string keyword) {
            this.getProductAsync(keyword, null);
        }
        
        public void getProductAsync(string keyword, object userState) {
            if ((this.onBegingetProductDelegate == null)) {
                this.onBegingetProductDelegate = new BeginOperationDelegate(this.OnBegingetProduct);
            }
            if ((this.onEndgetProductDelegate == null)) {
                this.onEndgetProductDelegate = new EndOperationDelegate(this.OnEndgetProduct);
            }
            if ((this.ongetProductCompletedDelegate == null)) {
                this.ongetProductCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetProductCompleted);
            }
            base.InvokeAsync(this.onBegingetProductDelegate, new object[] {
                        keyword}, this.onEndgetProductDelegate, this.ongetProductCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.ProductManager.ProductManagerPortType.BegingetProductByBrand(LateralMenus.ProductManager.getProductByBrandRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetProductByBrand(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetProductByBrand(string brand, System.AsyncCallback callback, object asyncState) {
            LateralMenus.ProductManager.getProductByBrandRequest inValue = new LateralMenus.ProductManager.getProductByBrandRequest();
            inValue.brand = brand;
            return ((LateralMenus.ProductManager.ProductManagerPortType)(this)).BegingetProductByBrand(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.ProductManager.getProductByBrandResponse LateralMenus.ProductManager.ProductManagerPortType.EndgetProductByBrand(System.IAsyncResult result) {
            return base.Channel.EndgetProductByBrand(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private LateralMenus.ProductManager.Product[] EndgetProductByBrand(System.IAsyncResult result) {
            LateralMenus.ProductManager.getProductByBrandResponse retVal = ((LateralMenus.ProductManager.ProductManagerPortType)(this)).EndgetProductByBrand(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetProductByBrand(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string brand = ((string)(inValues[0]));
            return this.BegingetProductByBrand(brand, callback, asyncState);
        }
        
        private object[] OnEndgetProductByBrand(System.IAsyncResult result) {
            LateralMenus.ProductManager.Product[] retVal = this.EndgetProductByBrand(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetProductByBrandCompleted(object state) {
            if ((this.getProductByBrandCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getProductByBrandCompleted(this, new getProductByBrandCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getProductByBrandAsync(string brand) {
            this.getProductByBrandAsync(brand, null);
        }
        
        public void getProductByBrandAsync(string brand, object userState) {
            if ((this.onBegingetProductByBrandDelegate == null)) {
                this.onBegingetProductByBrandDelegate = new BeginOperationDelegate(this.OnBegingetProductByBrand);
            }
            if ((this.onEndgetProductByBrandDelegate == null)) {
                this.onEndgetProductByBrandDelegate = new EndOperationDelegate(this.OnEndgetProductByBrand);
            }
            if ((this.ongetProductByBrandCompletedDelegate == null)) {
                this.ongetProductByBrandCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetProductByBrandCompleted);
            }
            base.InvokeAsync(this.onBegingetProductByBrandDelegate, new object[] {
                        brand}, this.onEndgetProductByBrandDelegate, this.ongetProductByBrandCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.ProductManager.ProductManagerPortType.BeginupdateProduct(LateralMenus.ProductManager.updateProductRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateProduct(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginupdateProduct(int id, string name, int ean, string picture, string brand, System.AsyncCallback callback, object asyncState) {
            LateralMenus.ProductManager.updateProductRequest inValue = new LateralMenus.ProductManager.updateProductRequest();
            inValue.id = id;
            inValue.name = name;
            inValue.ean = ean;
            inValue.picture = picture;
            inValue.brand = brand;
            return ((LateralMenus.ProductManager.ProductManagerPortType)(this)).BeginupdateProduct(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.ProductManager.updateProductResponse LateralMenus.ProductManager.ProductManagerPortType.EndupdateProduct(System.IAsyncResult result) {
            return base.Channel.EndupdateProduct(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndupdateProduct(System.IAsyncResult result) {
            LateralMenus.ProductManager.updateProductResponse retVal = ((LateralMenus.ProductManager.ProductManagerPortType)(this)).EndupdateProduct(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginupdateProduct(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            string name = ((string)(inValues[1]));
            int ean = ((int)(inValues[2]));
            string picture = ((string)(inValues[3]));
            string brand = ((string)(inValues[4]));
            return this.BeginupdateProduct(id, name, ean, picture, brand, callback, asyncState);
        }
        
        private object[] OnEndupdateProduct(System.IAsyncResult result) {
            bool retVal = this.EndupdateProduct(result);
            return new object[] {
                    retVal};
        }
        
        private void OnupdateProductCompleted(object state) {
            if ((this.updateProductCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateProductCompleted(this, new updateProductCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateProductAsync(int id, string name, int ean, string picture, string brand) {
            this.updateProductAsync(id, name, ean, picture, brand, null);
        }
        
        public void updateProductAsync(int id, string name, int ean, string picture, string brand, object userState) {
            if ((this.onBeginupdateProductDelegate == null)) {
                this.onBeginupdateProductDelegate = new BeginOperationDelegate(this.OnBeginupdateProduct);
            }
            if ((this.onEndupdateProductDelegate == null)) {
                this.onEndupdateProductDelegate = new EndOperationDelegate(this.OnEndupdateProduct);
            }
            if ((this.onupdateProductCompletedDelegate == null)) {
                this.onupdateProductCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateProductCompleted);
            }
            base.InvokeAsync(this.onBeginupdateProductDelegate, new object[] {
                        id,
                        name,
                        ean,
                        picture,
                        brand}, this.onEndupdateProductDelegate, this.onupdateProductCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.ProductManager.ProductManagerPortType.BeginregisterProduct(LateralMenus.ProductManager.registerProductRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginregisterProduct(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginregisterProduct(string name, int ean, string picture, string brand, System.AsyncCallback callback, object asyncState) {
            LateralMenus.ProductManager.registerProductRequest inValue = new LateralMenus.ProductManager.registerProductRequest();
            inValue.name = name;
            inValue.ean = ean;
            inValue.picture = picture;
            inValue.brand = brand;
            return ((LateralMenus.ProductManager.ProductManagerPortType)(this)).BeginregisterProduct(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.ProductManager.registerProductResponse LateralMenus.ProductManager.ProductManagerPortType.EndregisterProduct(System.IAsyncResult result) {
            return base.Channel.EndregisterProduct(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private int EndregisterProduct(System.IAsyncResult result) {
            LateralMenus.ProductManager.registerProductResponse retVal = ((LateralMenus.ProductManager.ProductManagerPortType)(this)).EndregisterProduct(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginregisterProduct(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            int ean = ((int)(inValues[1]));
            string picture = ((string)(inValues[2]));
            string brand = ((string)(inValues[3]));
            return this.BeginregisterProduct(name, ean, picture, brand, callback, asyncState);
        }
        
        private object[] OnEndregisterProduct(System.IAsyncResult result) {
            int retVal = this.EndregisterProduct(result);
            return new object[] {
                    retVal};
        }
        
        private void OnregisterProductCompleted(object state) {
            if ((this.registerProductCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.registerProductCompleted(this, new registerProductCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void registerProductAsync(string name, int ean, string picture, string brand) {
            this.registerProductAsync(name, ean, picture, brand, null);
        }
        
        public void registerProductAsync(string name, int ean, string picture, string brand, object userState) {
            if ((this.onBeginregisterProductDelegate == null)) {
                this.onBeginregisterProductDelegate = new BeginOperationDelegate(this.OnBeginregisterProduct);
            }
            if ((this.onEndregisterProductDelegate == null)) {
                this.onEndregisterProductDelegate = new EndOperationDelegate(this.OnEndregisterProduct);
            }
            if ((this.onregisterProductCompletedDelegate == null)) {
                this.onregisterProductCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnregisterProductCompleted);
            }
            base.InvokeAsync(this.onBeginregisterProductDelegate, new object[] {
                        name,
                        ean,
                        picture,
                        brand}, this.onEndregisterProductDelegate, this.onregisterProductCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.ProductManager.ProductManagerPortType.BegingetProductByEAN(LateralMenus.ProductManager.getProductByEANRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetProductByEAN(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetProductByEAN(int ean, System.AsyncCallback callback, object asyncState) {
            LateralMenus.ProductManager.getProductByEANRequest inValue = new LateralMenus.ProductManager.getProductByEANRequest();
            inValue.ean = ean;
            return ((LateralMenus.ProductManager.ProductManagerPortType)(this)).BegingetProductByEAN(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.ProductManager.getProductByEANResponse LateralMenus.ProductManager.ProductManagerPortType.EndgetProductByEAN(System.IAsyncResult result) {
            return base.Channel.EndgetProductByEAN(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private LateralMenus.ProductManager.Product EndgetProductByEAN(System.IAsyncResult result) {
            LateralMenus.ProductManager.getProductByEANResponse retVal = ((LateralMenus.ProductManager.ProductManagerPortType)(this)).EndgetProductByEAN(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetProductByEAN(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int ean = ((int)(inValues[0]));
            return this.BegingetProductByEAN(ean, callback, asyncState);
        }
        
        private object[] OnEndgetProductByEAN(System.IAsyncResult result) {
            LateralMenus.ProductManager.Product retVal = this.EndgetProductByEAN(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetProductByEANCompleted(object state) {
            if ((this.getProductByEANCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getProductByEANCompleted(this, new getProductByEANCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getProductByEANAsync(int ean) {
            this.getProductByEANAsync(ean, null);
        }
        
        public void getProductByEANAsync(int ean, object userState) {
            if ((this.onBegingetProductByEANDelegate == null)) {
                this.onBegingetProductByEANDelegate = new BeginOperationDelegate(this.OnBegingetProductByEAN);
            }
            if ((this.onEndgetProductByEANDelegate == null)) {
                this.onEndgetProductByEANDelegate = new EndOperationDelegate(this.OnEndgetProductByEAN);
            }
            if ((this.ongetProductByEANCompletedDelegate == null)) {
                this.ongetProductByEANCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetProductByEANCompleted);
            }
            base.InvokeAsync(this.onBegingetProductByEANDelegate, new object[] {
                        ean}, this.onEndgetProductByEANDelegate, this.ongetProductByEANCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.ProductManager.ProductManagerPortType.BegingetProductByName(LateralMenus.ProductManager.getProductByNameRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetProductByName(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetProductByName(string name, System.AsyncCallback callback, object asyncState) {
            LateralMenus.ProductManager.getProductByNameRequest inValue = new LateralMenus.ProductManager.getProductByNameRequest();
            inValue.name = name;
            return ((LateralMenus.ProductManager.ProductManagerPortType)(this)).BegingetProductByName(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.ProductManager.getProductByNameResponse LateralMenus.ProductManager.ProductManagerPortType.EndgetProductByName(System.IAsyncResult result) {
            return base.Channel.EndgetProductByName(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private LateralMenus.ProductManager.Product[] EndgetProductByName(System.IAsyncResult result) {
            LateralMenus.ProductManager.getProductByNameResponse retVal = ((LateralMenus.ProductManager.ProductManagerPortType)(this)).EndgetProductByName(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetProductByName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            return this.BegingetProductByName(name, callback, asyncState);
        }
        
        private object[] OnEndgetProductByName(System.IAsyncResult result) {
            LateralMenus.ProductManager.Product[] retVal = this.EndgetProductByName(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetProductByNameCompleted(object state) {
            if ((this.getProductByNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getProductByNameCompleted(this, new getProductByNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getProductByNameAsync(string name) {
            this.getProductByNameAsync(name, null);
        }
        
        public void getProductByNameAsync(string name, object userState) {
            if ((this.onBegingetProductByNameDelegate == null)) {
                this.onBegingetProductByNameDelegate = new BeginOperationDelegate(this.OnBegingetProductByName);
            }
            if ((this.onEndgetProductByNameDelegate == null)) {
                this.onEndgetProductByNameDelegate = new EndOperationDelegate(this.OnEndgetProductByName);
            }
            if ((this.ongetProductByNameCompletedDelegate == null)) {
                this.ongetProductByNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetProductByNameCompleted);
            }
            base.InvokeAsync(this.onBegingetProductByNameDelegate, new object[] {
                        name}, this.onEndgetProductByNameDelegate, this.ongetProductByNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.ProductManager.ProductManagerPortType.BegindeleteProduct(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindeleteProduct(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool LateralMenus.ProductManager.ProductManagerPortType.EnddeleteProduct(System.IAsyncResult result) {
            return base.Channel.EnddeleteProduct(result);
        }
        
        private System.IAsyncResult OnBegindeleteProduct(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((LateralMenus.ProductManager.ProductManagerPortType)(this)).BegindeleteProduct(id, callback, asyncState);
        }
        
        private object[] OnEnddeleteProduct(System.IAsyncResult result) {
            bool retVal = ((LateralMenus.ProductManager.ProductManagerPortType)(this)).EnddeleteProduct(result);
            return new object[] {
                    retVal};
        }
        
        private void OndeleteProductCompleted(object state) {
            if ((this.deleteProductCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.deleteProductCompleted(this, new deleteProductCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void deleteProductAsync(int id) {
            this.deleteProductAsync(id, null);
        }
        
        public void deleteProductAsync(int id, object userState) {
            if ((this.onBegindeleteProductDelegate == null)) {
                this.onBegindeleteProductDelegate = new BeginOperationDelegate(this.OnBegindeleteProduct);
            }
            if ((this.onEnddeleteProductDelegate == null)) {
                this.onEnddeleteProductDelegate = new EndOperationDelegate(this.OnEnddeleteProduct);
            }
            if ((this.ondeleteProductCompletedDelegate == null)) {
                this.ondeleteProductCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndeleteProductCompleted);
            }
            base.InvokeAsync(this.onBegindeleteProductDelegate, new object[] {
                        id}, this.onEnddeleteProductDelegate, this.ondeleteProductCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.ProductManager.ProductManagerPortType.BegingetProductInfo(LateralMenus.ProductManager.getProductInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetProductInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetProductInfo(int id, System.AsyncCallback callback, object asyncState) {
            LateralMenus.ProductManager.getProductInfoRequest inValue = new LateralMenus.ProductManager.getProductInfoRequest();
            inValue.id = id;
            return ((LateralMenus.ProductManager.ProductManagerPortType)(this)).BegingetProductInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.ProductManager.getProductInfoResponse LateralMenus.ProductManager.ProductManagerPortType.EndgetProductInfo(System.IAsyncResult result) {
            return base.Channel.EndgetProductInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private LateralMenus.ProductManager.Product EndgetProductInfo(System.IAsyncResult result) {
            LateralMenus.ProductManager.getProductInfoResponse retVal = ((LateralMenus.ProductManager.ProductManagerPortType)(this)).EndgetProductInfo(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetProductInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return this.BegingetProductInfo(id, callback, asyncState);
        }
        
        private object[] OnEndgetProductInfo(System.IAsyncResult result) {
            LateralMenus.ProductManager.Product retVal = this.EndgetProductInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetProductInfoCompleted(object state) {
            if ((this.getProductInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getProductInfoCompleted(this, new getProductInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getProductInfoAsync(int id) {
            this.getProductInfoAsync(id, null);
        }
        
        public void getProductInfoAsync(int id, object userState) {
            if ((this.onBegingetProductInfoDelegate == null)) {
                this.onBegingetProductInfoDelegate = new BeginOperationDelegate(this.OnBegingetProductInfo);
            }
            if ((this.onEndgetProductInfoDelegate == null)) {
                this.onEndgetProductInfoDelegate = new EndOperationDelegate(this.OnEndgetProductInfo);
            }
            if ((this.ongetProductInfoCompletedDelegate == null)) {
                this.ongetProductInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetProductInfoCompleted);
            }
            base.InvokeAsync(this.onBegingetProductInfoDelegate, new object[] {
                        id}, this.onEndgetProductInfoDelegate, this.ongetProductInfoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override LateralMenus.ProductManager.ProductManagerPortType CreateChannel() {
            return new ProductManagerPortTypeClientChannel(this);
        }
        
        private class ProductManagerPortTypeClientChannel : ChannelBase<LateralMenus.ProductManager.ProductManagerPortType>, LateralMenus.ProductManager.ProductManagerPortType {
            
            public ProductManagerPortTypeClientChannel(System.ServiceModel.ClientBase<LateralMenus.ProductManager.ProductManagerPortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetProduct(LateralMenus.ProductManager.getProductRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getProduct", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.ProductManager.getProductResponse EndgetProduct(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.ProductManager.getProductResponse _result = ((LateralMenus.ProductManager.getProductResponse)(base.EndInvoke("getProduct", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetProductByBrand(LateralMenus.ProductManager.getProductByBrandRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getProductByBrand", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.ProductManager.getProductByBrandResponse EndgetProductByBrand(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.ProductManager.getProductByBrandResponse _result = ((LateralMenus.ProductManager.getProductByBrandResponse)(base.EndInvoke("getProductByBrand", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginupdateProduct(LateralMenus.ProductManager.updateProductRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("updateProduct", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.ProductManager.updateProductResponse EndupdateProduct(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.ProductManager.updateProductResponse _result = ((LateralMenus.ProductManager.updateProductResponse)(base.EndInvoke("updateProduct", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginregisterProduct(LateralMenus.ProductManager.registerProductRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("registerProduct", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.ProductManager.registerProductResponse EndregisterProduct(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.ProductManager.registerProductResponse _result = ((LateralMenus.ProductManager.registerProductResponse)(base.EndInvoke("registerProduct", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetProductByEAN(LateralMenus.ProductManager.getProductByEANRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getProductByEAN", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.ProductManager.getProductByEANResponse EndgetProductByEAN(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.ProductManager.getProductByEANResponse _result = ((LateralMenus.ProductManager.getProductByEANResponse)(base.EndInvoke("getProductByEAN", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetProductByName(LateralMenus.ProductManager.getProductByNameRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getProductByName", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.ProductManager.getProductByNameResponse EndgetProductByName(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.ProductManager.getProductByNameResponse _result = ((LateralMenus.ProductManager.getProductByNameResponse)(base.EndInvoke("getProductByName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegindeleteProduct(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("deleteProduct", _args, callback, asyncState);
                return _result;
            }
            
            public bool EnddeleteProduct(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("deleteProduct", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetProductInfo(LateralMenus.ProductManager.getProductInfoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getProductInfo", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.ProductManager.getProductInfoResponse EndgetProductInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.ProductManager.getProductInfoResponse _result = ((LateralMenus.ProductManager.getProductInfoResponse)(base.EndInvoke("getProductInfo", _args, result)));
                return _result;
            }
        }
    }
}
