//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace LateralMenus.GlobalManager {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://manager.entity.upreal", ConfigurationName="GlobalManager.GlobalManagerPortType")]
    public interface GlobalManagerPortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:getRate", ReplyAction="urn:getRateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetRate(LateralMenus.GlobalManager.getRateRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.GlobalManager.getRateResponse EndgetRate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:createNewsComment", ReplyAction="urn:createNewsCommentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegincreateNewsComment(LateralMenus.GlobalManager.createNewsCommentRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.GlobalManager.createNewsCommentResponse EndcreateNewsComment(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:sumMarkNews", ReplyAction="urn:sumMarkNewsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginsumMarkNews(int id_article, System.AsyncCallback callback, object asyncState);
        
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EndsumMarkNews(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:getRateById", ReplyAction="urn:getRateByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetRateById(LateralMenus.GlobalManager.getRateByIdRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.GlobalManager.getRateByIdResponse EndgetRateById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Test", ReplyAction="urn:TestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginTest(LateralMenus.GlobalManager.TestRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.GlobalManager.TestResponse EndTest(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:rateNews", ReplyAction="urn:rateNewsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginrateNews(int id_user, int id_target, int mark, System.AsyncCallback callback, object asyncState);
        
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool EndrateNews(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:searchKeyword", ReplyAction="urn:searchKeywordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginsearchKeyword(LateralMenus.GlobalManager.searchKeywordRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.GlobalManager.searchKeywordResponse EndsearchKeyword(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:searchNews", ReplyAction="urn:searchNewsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginsearchNews(LateralMenus.GlobalManager.searchNewsRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.GlobalManager.searchNewsResponse EndsearchNews(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:getNewsInfo", ReplyAction="urn:getNewsInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetNewsInfo(LateralMenus.GlobalManager.getNewsInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        LateralMenus.GlobalManager.getNewsInfoResponse EndgetNewsInfo(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pojo.entity.upreal/xsd")]
    public partial class Rate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activeField;
        
        private bool activeFieldSpecified;
        
        private string commentaryField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private int downField;
        
        private bool downFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int id_userField;
        
        private bool id_userFieldSpecified;
        
        private int markField;
        
        private bool markFieldSpecified;
        
        private int upField;
        
        private bool upFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
                this.RaisePropertyChanged("activeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string commentary {
            get {
                return this.commentaryField;
            }
            set {
                this.commentaryField = value;
                this.RaisePropertyChanged("commentary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int down {
            get {
                return this.downField;
            }
            set {
                this.downField = value;
                this.RaisePropertyChanged("down");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool downSpecified {
            get {
                return this.downFieldSpecified;
            }
            set {
                this.downFieldSpecified = value;
                this.RaisePropertyChanged("downSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int id_user {
            get {
                return this.id_userField;
            }
            set {
                this.id_userField = value;
                this.RaisePropertyChanged("id_user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_userSpecified {
            get {
                return this.id_userFieldSpecified;
            }
            set {
                this.id_userFieldSpecified = value;
                this.RaisePropertyChanged("id_userSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
                this.RaisePropertyChanged("mark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool markSpecified {
            get {
                return this.markFieldSpecified;
            }
            set {
                this.markFieldSpecified = value;
                this.RaisePropertyChanged("markSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int up {
            get {
                return this.upField;
            }
            set {
                this.upField = value;
                this.RaisePropertyChanged("up");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool upSpecified {
            get {
                return this.upFieldSpecified;
            }
            set {
                this.upFieldSpecified = value;
                this.RaisePropertyChanged("upSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pojo.entity.upreal/xsd")]
    public partial class Article : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bodyField;
        
        private System.Nullable<System.DateTime> creationField;
        
        private bool creationFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> creation {
            get {
                return this.creationField;
            }
            set {
                this.creationField = value;
                this.RaisePropertyChanged("creation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationSpecified {
            get {
                return this.creationFieldSpecified;
            }
            set {
                this.creationFieldSpecified = value;
                this.RaisePropertyChanged("creationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRate", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        public int id_user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=1)]
        public int id_product;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=2)]
        public int id_ovr_rate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=3)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=4)]
        public int id_article;
        
        public getRateRequest() {
        }
        
        public getRateRequest(int id_user, int id_product, int id_ovr_rate, int type, int id_article) {
            this.id_user = id_user;
            this.id_product = id_product;
            this.id_ovr_rate = id_ovr_rate;
            this.type = type;
            this.id_article = id_article;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRateResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public LateralMenus.GlobalManager.Rate[] @return;
        
        public getRateResponse() {
        }
        
        public getRateResponse(LateralMenus.GlobalManager.Rate[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createNewsComment", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class createNewsCommentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        public int id_user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=1)]
        public int id_target;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string commentary;
        
        public createNewsCommentRequest() {
        }
        
        public createNewsCommentRequest(int id_user, int id_target, string commentary) {
            this.id_user = id_user;
            this.id_target = id_target;
            this.commentary = commentary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createNewsCommentResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class createNewsCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        public int @return;
        
        public createNewsCommentResponse() {
        }
        
        public createNewsCommentResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRateById", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getRateByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        public int id;
        
        public getRateByIdRequest() {
        }
        
        public getRateByIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRateByIdResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getRateByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LateralMenus.GlobalManager.Rate @return;
        
        public getRateByIdResponse() {
        }
        
        public getRateByIdResponse(LateralMenus.GlobalManager.Rate @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public TestResponse() {
        }
        
        public TestResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchKeyword", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class searchKeywordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string keyword;
        
        public searchKeywordRequest() {
        }
        
        public searchKeywordRequest(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchKeywordResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class searchKeywordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public object[] @return;
        
        public searchKeywordResponse() {
        }
        
        public searchKeywordResponse(object[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchNews", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class searchNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string keyword;
        
        public searchNewsRequest() {
        }
        
        public searchNewsRequest(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchNewsResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class searchNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public LateralMenus.GlobalManager.Article[] @return;
        
        public searchNewsResponse() {
        }
        
        public searchNewsResponse(LateralMenus.GlobalManager.Article[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNewsInfo", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getNewsInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        public int id;
        
        public getNewsInfoRequest() {
        }
        
        public getNewsInfoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNewsInfoResponse", WrapperNamespace="http://manager.entity.upreal", IsWrapped=true)]
    public partial class getNewsInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.entity.upreal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LateralMenus.GlobalManager.Article @return;
        
        public getNewsInfoResponse() {
        }
        
        public getNewsInfoResponse(LateralMenus.GlobalManager.Article @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GlobalManagerPortTypeChannel : LateralMenus.GlobalManager.GlobalManagerPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LateralMenus.GlobalManager.Rate[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LateralMenus.GlobalManager.Rate[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class createNewsCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public createNewsCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sumMarkNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public sumMarkNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getRateByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getRateByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LateralMenus.GlobalManager.Rate Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LateralMenus.GlobalManager.Rate)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class rateNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public rateNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class searchKeywordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public searchKeywordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public object[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class searchNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public searchNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LateralMenus.GlobalManager.Article[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LateralMenus.GlobalManager.Article[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getNewsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getNewsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LateralMenus.GlobalManager.Article Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LateralMenus.GlobalManager.Article)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlobalManagerPortTypeClient : System.ServiceModel.ClientBase<LateralMenus.GlobalManager.GlobalManagerPortType>, LateralMenus.GlobalManager.GlobalManagerPortType {
        
        private BeginOperationDelegate onBegingetRateDelegate;
        
        private EndOperationDelegate onEndgetRateDelegate;
        
        private System.Threading.SendOrPostCallback ongetRateCompletedDelegate;
        
        private BeginOperationDelegate onBegincreateNewsCommentDelegate;
        
        private EndOperationDelegate onEndcreateNewsCommentDelegate;
        
        private System.Threading.SendOrPostCallback oncreateNewsCommentCompletedDelegate;
        
        private BeginOperationDelegate onBeginsumMarkNewsDelegate;
        
        private EndOperationDelegate onEndsumMarkNewsDelegate;
        
        private System.Threading.SendOrPostCallback onsumMarkNewsCompletedDelegate;
        
        private BeginOperationDelegate onBegingetRateByIdDelegate;
        
        private EndOperationDelegate onEndgetRateByIdDelegate;
        
        private System.Threading.SendOrPostCallback ongetRateByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginTestDelegate;
        
        private EndOperationDelegate onEndTestDelegate;
        
        private System.Threading.SendOrPostCallback onTestCompletedDelegate;
        
        private BeginOperationDelegate onBeginrateNewsDelegate;
        
        private EndOperationDelegate onEndrateNewsDelegate;
        
        private System.Threading.SendOrPostCallback onrateNewsCompletedDelegate;
        
        private BeginOperationDelegate onBeginsearchKeywordDelegate;
        
        private EndOperationDelegate onEndsearchKeywordDelegate;
        
        private System.Threading.SendOrPostCallback onsearchKeywordCompletedDelegate;
        
        private BeginOperationDelegate onBeginsearchNewsDelegate;
        
        private EndOperationDelegate onEndsearchNewsDelegate;
        
        private System.Threading.SendOrPostCallback onsearchNewsCompletedDelegate;
        
        private BeginOperationDelegate onBegingetNewsInfoDelegate;
        
        private EndOperationDelegate onEndgetNewsInfoDelegate;
        
        private System.Threading.SendOrPostCallback ongetNewsInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public GlobalManagerPortTypeClient() {
        }
        
        public GlobalManagerPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GlobalManagerPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalManagerPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalManagerPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getRateCompletedEventArgs> getRateCompleted;
        
        public event System.EventHandler<createNewsCommentCompletedEventArgs> createNewsCommentCompleted;
        
        public event System.EventHandler<sumMarkNewsCompletedEventArgs> sumMarkNewsCompleted;
        
        public event System.EventHandler<getRateByIdCompletedEventArgs> getRateByIdCompleted;
        
        public event System.EventHandler<TestCompletedEventArgs> TestCompleted;
        
        public event System.EventHandler<rateNewsCompletedEventArgs> rateNewsCompleted;
        
        public event System.EventHandler<searchKeywordCompletedEventArgs> searchKeywordCompleted;
        
        public event System.EventHandler<searchNewsCompletedEventArgs> searchNewsCompleted;
        
        public event System.EventHandler<getNewsInfoCompletedEventArgs> getNewsInfoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.GlobalManager.GlobalManagerPortType.BegingetRate(LateralMenus.GlobalManager.getRateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetRate(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetRate(int id_user, int id_product, int id_ovr_rate, int type, int id_article, System.AsyncCallback callback, object asyncState) {
            LateralMenus.GlobalManager.getRateRequest inValue = new LateralMenus.GlobalManager.getRateRequest();
            inValue.id_user = id_user;
            inValue.id_product = id_product;
            inValue.id_ovr_rate = id_ovr_rate;
            inValue.type = type;
            inValue.id_article = id_article;
            return ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).BegingetRate(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.GlobalManager.getRateResponse LateralMenus.GlobalManager.GlobalManagerPortType.EndgetRate(System.IAsyncResult result) {
            return base.Channel.EndgetRate(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private LateralMenus.GlobalManager.Rate[] EndgetRate(System.IAsyncResult result) {
            LateralMenus.GlobalManager.getRateResponse retVal = ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).EndgetRate(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetRate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id_user = ((int)(inValues[0]));
            int id_product = ((int)(inValues[1]));
            int id_ovr_rate = ((int)(inValues[2]));
            int type = ((int)(inValues[3]));
            int id_article = ((int)(inValues[4]));
            return this.BegingetRate(id_user, id_product, id_ovr_rate, type, id_article, callback, asyncState);
        }
        
        private object[] OnEndgetRate(System.IAsyncResult result) {
            LateralMenus.GlobalManager.Rate[] retVal = this.EndgetRate(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetRateCompleted(object state) {
            if ((this.getRateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getRateCompleted(this, new getRateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getRateAsync(int id_user, int id_product, int id_ovr_rate, int type, int id_article) {
            this.getRateAsync(id_user, id_product, id_ovr_rate, type, id_article, null);
        }
        
        public void getRateAsync(int id_user, int id_product, int id_ovr_rate, int type, int id_article, object userState) {
            if ((this.onBegingetRateDelegate == null)) {
                this.onBegingetRateDelegate = new BeginOperationDelegate(this.OnBegingetRate);
            }
            if ((this.onEndgetRateDelegate == null)) {
                this.onEndgetRateDelegate = new EndOperationDelegate(this.OnEndgetRate);
            }
            if ((this.ongetRateCompletedDelegate == null)) {
                this.ongetRateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetRateCompleted);
            }
            base.InvokeAsync(this.onBegingetRateDelegate, new object[] {
                        id_user,
                        id_product,
                        id_ovr_rate,
                        type,
                        id_article}, this.onEndgetRateDelegate, this.ongetRateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.GlobalManager.GlobalManagerPortType.BegincreateNewsComment(LateralMenus.GlobalManager.createNewsCommentRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegincreateNewsComment(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegincreateNewsComment(int id_user, int id_target, string commentary, System.AsyncCallback callback, object asyncState) {
            LateralMenus.GlobalManager.createNewsCommentRequest inValue = new LateralMenus.GlobalManager.createNewsCommentRequest();
            inValue.id_user = id_user;
            inValue.id_target = id_target;
            inValue.commentary = commentary;
            return ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).BegincreateNewsComment(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.GlobalManager.createNewsCommentResponse LateralMenus.GlobalManager.GlobalManagerPortType.EndcreateNewsComment(System.IAsyncResult result) {
            return base.Channel.EndcreateNewsComment(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private int EndcreateNewsComment(System.IAsyncResult result) {
            LateralMenus.GlobalManager.createNewsCommentResponse retVal = ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).EndcreateNewsComment(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegincreateNewsComment(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id_user = ((int)(inValues[0]));
            int id_target = ((int)(inValues[1]));
            string commentary = ((string)(inValues[2]));
            return this.BegincreateNewsComment(id_user, id_target, commentary, callback, asyncState);
        }
        
        private object[] OnEndcreateNewsComment(System.IAsyncResult result) {
            int retVal = this.EndcreateNewsComment(result);
            return new object[] {
                    retVal};
        }
        
        private void OncreateNewsCommentCompleted(object state) {
            if ((this.createNewsCommentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.createNewsCommentCompleted(this, new createNewsCommentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void createNewsCommentAsync(int id_user, int id_target, string commentary) {
            this.createNewsCommentAsync(id_user, id_target, commentary, null);
        }
        
        public void createNewsCommentAsync(int id_user, int id_target, string commentary, object userState) {
            if ((this.onBegincreateNewsCommentDelegate == null)) {
                this.onBegincreateNewsCommentDelegate = new BeginOperationDelegate(this.OnBegincreateNewsComment);
            }
            if ((this.onEndcreateNewsCommentDelegate == null)) {
                this.onEndcreateNewsCommentDelegate = new EndOperationDelegate(this.OnEndcreateNewsComment);
            }
            if ((this.oncreateNewsCommentCompletedDelegate == null)) {
                this.oncreateNewsCommentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncreateNewsCommentCompleted);
            }
            base.InvokeAsync(this.onBegincreateNewsCommentDelegate, new object[] {
                        id_user,
                        id_target,
                        commentary}, this.onEndcreateNewsCommentDelegate, this.oncreateNewsCommentCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.GlobalManager.GlobalManagerPortType.BeginsumMarkNews(int id_article, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsumMarkNews(id_article, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int LateralMenus.GlobalManager.GlobalManagerPortType.EndsumMarkNews(System.IAsyncResult result) {
            return base.Channel.EndsumMarkNews(result);
        }
        
        private System.IAsyncResult OnBeginsumMarkNews(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id_article = ((int)(inValues[0]));
            return ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).BeginsumMarkNews(id_article, callback, asyncState);
        }
        
        private object[] OnEndsumMarkNews(System.IAsyncResult result) {
            int retVal = ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).EndsumMarkNews(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsumMarkNewsCompleted(object state) {
            if ((this.sumMarkNewsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.sumMarkNewsCompleted(this, new sumMarkNewsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void sumMarkNewsAsync(int id_article) {
            this.sumMarkNewsAsync(id_article, null);
        }
        
        public void sumMarkNewsAsync(int id_article, object userState) {
            if ((this.onBeginsumMarkNewsDelegate == null)) {
                this.onBeginsumMarkNewsDelegate = new BeginOperationDelegate(this.OnBeginsumMarkNews);
            }
            if ((this.onEndsumMarkNewsDelegate == null)) {
                this.onEndsumMarkNewsDelegate = new EndOperationDelegate(this.OnEndsumMarkNews);
            }
            if ((this.onsumMarkNewsCompletedDelegate == null)) {
                this.onsumMarkNewsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsumMarkNewsCompleted);
            }
            base.InvokeAsync(this.onBeginsumMarkNewsDelegate, new object[] {
                        id_article}, this.onEndsumMarkNewsDelegate, this.onsumMarkNewsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.GlobalManager.GlobalManagerPortType.BegingetRateById(LateralMenus.GlobalManager.getRateByIdRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetRateById(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetRateById(int id, System.AsyncCallback callback, object asyncState) {
            LateralMenus.GlobalManager.getRateByIdRequest inValue = new LateralMenus.GlobalManager.getRateByIdRequest();
            inValue.id = id;
            return ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).BegingetRateById(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.GlobalManager.getRateByIdResponse LateralMenus.GlobalManager.GlobalManagerPortType.EndgetRateById(System.IAsyncResult result) {
            return base.Channel.EndgetRateById(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private LateralMenus.GlobalManager.Rate EndgetRateById(System.IAsyncResult result) {
            LateralMenus.GlobalManager.getRateByIdResponse retVal = ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).EndgetRateById(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetRateById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return this.BegingetRateById(id, callback, asyncState);
        }
        
        private object[] OnEndgetRateById(System.IAsyncResult result) {
            LateralMenus.GlobalManager.Rate retVal = this.EndgetRateById(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetRateByIdCompleted(object state) {
            if ((this.getRateByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getRateByIdCompleted(this, new getRateByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getRateByIdAsync(int id) {
            this.getRateByIdAsync(id, null);
        }
        
        public void getRateByIdAsync(int id, object userState) {
            if ((this.onBegingetRateByIdDelegate == null)) {
                this.onBegingetRateByIdDelegate = new BeginOperationDelegate(this.OnBegingetRateById);
            }
            if ((this.onEndgetRateByIdDelegate == null)) {
                this.onEndgetRateByIdDelegate = new EndOperationDelegate(this.OnEndgetRateById);
            }
            if ((this.ongetRateByIdCompletedDelegate == null)) {
                this.ongetRateByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetRateByIdCompleted);
            }
            base.InvokeAsync(this.onBegingetRateByIdDelegate, new object[] {
                        id}, this.onEndgetRateByIdDelegate, this.ongetRateByIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.GlobalManager.GlobalManagerPortType.BeginTest(LateralMenus.GlobalManager.TestRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTest(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginTest(System.AsyncCallback callback, object asyncState) {
            LateralMenus.GlobalManager.TestRequest inValue = new LateralMenus.GlobalManager.TestRequest();
            return ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).BeginTest(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.GlobalManager.TestResponse LateralMenus.GlobalManager.GlobalManagerPortType.EndTest(System.IAsyncResult result) {
            return base.Channel.EndTest(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndTest(System.IAsyncResult result) {
            LateralMenus.GlobalManager.TestResponse retVal = ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).EndTest(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginTest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginTest(callback, asyncState);
        }
        
        private object[] OnEndTest(System.IAsyncResult result) {
            string retVal = this.EndTest(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestCompleted(object state) {
            if ((this.TestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestCompleted(this, new TestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        public void TestAsync(object userState) {
            if ((this.onBeginTestDelegate == null)) {
                this.onBeginTestDelegate = new BeginOperationDelegate(this.OnBeginTest);
            }
            if ((this.onEndTestDelegate == null)) {
                this.onEndTestDelegate = new EndOperationDelegate(this.OnEndTest);
            }
            if ((this.onTestCompletedDelegate == null)) {
                this.onTestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestCompleted);
            }
            base.InvokeAsync(this.onBeginTestDelegate, null, this.onEndTestDelegate, this.onTestCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.GlobalManager.GlobalManagerPortType.BeginrateNews(int id_user, int id_target, int mark, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginrateNews(id_user, id_target, mark, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool LateralMenus.GlobalManager.GlobalManagerPortType.EndrateNews(System.IAsyncResult result) {
            return base.Channel.EndrateNews(result);
        }
        
        private System.IAsyncResult OnBeginrateNews(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id_user = ((int)(inValues[0]));
            int id_target = ((int)(inValues[1]));
            int mark = ((int)(inValues[2]));
            return ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).BeginrateNews(id_user, id_target, mark, callback, asyncState);
        }
        
        private object[] OnEndrateNews(System.IAsyncResult result) {
            bool retVal = ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).EndrateNews(result);
            return new object[] {
                    retVal};
        }
        
        private void OnrateNewsCompleted(object state) {
            if ((this.rateNewsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.rateNewsCompleted(this, new rateNewsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void rateNewsAsync(int id_user, int id_target, int mark) {
            this.rateNewsAsync(id_user, id_target, mark, null);
        }
        
        public void rateNewsAsync(int id_user, int id_target, int mark, object userState) {
            if ((this.onBeginrateNewsDelegate == null)) {
                this.onBeginrateNewsDelegate = new BeginOperationDelegate(this.OnBeginrateNews);
            }
            if ((this.onEndrateNewsDelegate == null)) {
                this.onEndrateNewsDelegate = new EndOperationDelegate(this.OnEndrateNews);
            }
            if ((this.onrateNewsCompletedDelegate == null)) {
                this.onrateNewsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnrateNewsCompleted);
            }
            base.InvokeAsync(this.onBeginrateNewsDelegate, new object[] {
                        id_user,
                        id_target,
                        mark}, this.onEndrateNewsDelegate, this.onrateNewsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.GlobalManager.GlobalManagerPortType.BeginsearchKeyword(LateralMenus.GlobalManager.searchKeywordRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsearchKeyword(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginsearchKeyword(string keyword, System.AsyncCallback callback, object asyncState) {
            LateralMenus.GlobalManager.searchKeywordRequest inValue = new LateralMenus.GlobalManager.searchKeywordRequest();
            inValue.keyword = keyword;
            return ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).BeginsearchKeyword(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.GlobalManager.searchKeywordResponse LateralMenus.GlobalManager.GlobalManagerPortType.EndsearchKeyword(System.IAsyncResult result) {
            return base.Channel.EndsearchKeyword(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private object[] EndsearchKeyword(System.IAsyncResult result) {
            LateralMenus.GlobalManager.searchKeywordResponse retVal = ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).EndsearchKeyword(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginsearchKeyword(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string keyword = ((string)(inValues[0]));
            return this.BeginsearchKeyword(keyword, callback, asyncState);
        }
        
        private object[] OnEndsearchKeyword(System.IAsyncResult result) {
            object[] retVal = this.EndsearchKeyword(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsearchKeywordCompleted(object state) {
            if ((this.searchKeywordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.searchKeywordCompleted(this, new searchKeywordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void searchKeywordAsync(string keyword) {
            this.searchKeywordAsync(keyword, null);
        }
        
        public void searchKeywordAsync(string keyword, object userState) {
            if ((this.onBeginsearchKeywordDelegate == null)) {
                this.onBeginsearchKeywordDelegate = new BeginOperationDelegate(this.OnBeginsearchKeyword);
            }
            if ((this.onEndsearchKeywordDelegate == null)) {
                this.onEndsearchKeywordDelegate = new EndOperationDelegate(this.OnEndsearchKeyword);
            }
            if ((this.onsearchKeywordCompletedDelegate == null)) {
                this.onsearchKeywordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsearchKeywordCompleted);
            }
            base.InvokeAsync(this.onBeginsearchKeywordDelegate, new object[] {
                        keyword}, this.onEndsearchKeywordDelegate, this.onsearchKeywordCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.GlobalManager.GlobalManagerPortType.BeginsearchNews(LateralMenus.GlobalManager.searchNewsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsearchNews(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginsearchNews(string keyword, System.AsyncCallback callback, object asyncState) {
            LateralMenus.GlobalManager.searchNewsRequest inValue = new LateralMenus.GlobalManager.searchNewsRequest();
            inValue.keyword = keyword;
            return ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).BeginsearchNews(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.GlobalManager.searchNewsResponse LateralMenus.GlobalManager.GlobalManagerPortType.EndsearchNews(System.IAsyncResult result) {
            return base.Channel.EndsearchNews(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private LateralMenus.GlobalManager.Article[] EndsearchNews(System.IAsyncResult result) {
            LateralMenus.GlobalManager.searchNewsResponse retVal = ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).EndsearchNews(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginsearchNews(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string keyword = ((string)(inValues[0]));
            return this.BeginsearchNews(keyword, callback, asyncState);
        }
        
        private object[] OnEndsearchNews(System.IAsyncResult result) {
            LateralMenus.GlobalManager.Article[] retVal = this.EndsearchNews(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsearchNewsCompleted(object state) {
            if ((this.searchNewsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.searchNewsCompleted(this, new searchNewsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void searchNewsAsync(string keyword) {
            this.searchNewsAsync(keyword, null);
        }
        
        public void searchNewsAsync(string keyword, object userState) {
            if ((this.onBeginsearchNewsDelegate == null)) {
                this.onBeginsearchNewsDelegate = new BeginOperationDelegate(this.OnBeginsearchNews);
            }
            if ((this.onEndsearchNewsDelegate == null)) {
                this.onEndsearchNewsDelegate = new EndOperationDelegate(this.OnEndsearchNews);
            }
            if ((this.onsearchNewsCompletedDelegate == null)) {
                this.onsearchNewsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsearchNewsCompleted);
            }
            base.InvokeAsync(this.onBeginsearchNewsDelegate, new object[] {
                        keyword}, this.onEndsearchNewsDelegate, this.onsearchNewsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LateralMenus.GlobalManager.GlobalManagerPortType.BegingetNewsInfo(LateralMenus.GlobalManager.getNewsInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetNewsInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetNewsInfo(int id, System.AsyncCallback callback, object asyncState) {
            LateralMenus.GlobalManager.getNewsInfoRequest inValue = new LateralMenus.GlobalManager.getNewsInfoRequest();
            inValue.id = id;
            return ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).BegingetNewsInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LateralMenus.GlobalManager.getNewsInfoResponse LateralMenus.GlobalManager.GlobalManagerPortType.EndgetNewsInfo(System.IAsyncResult result) {
            return base.Channel.EndgetNewsInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private LateralMenus.GlobalManager.Article EndgetNewsInfo(System.IAsyncResult result) {
            LateralMenus.GlobalManager.getNewsInfoResponse retVal = ((LateralMenus.GlobalManager.GlobalManagerPortType)(this)).EndgetNewsInfo(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetNewsInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return this.BegingetNewsInfo(id, callback, asyncState);
        }
        
        private object[] OnEndgetNewsInfo(System.IAsyncResult result) {
            LateralMenus.GlobalManager.Article retVal = this.EndgetNewsInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetNewsInfoCompleted(object state) {
            if ((this.getNewsInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getNewsInfoCompleted(this, new getNewsInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getNewsInfoAsync(int id) {
            this.getNewsInfoAsync(id, null);
        }
        
        public void getNewsInfoAsync(int id, object userState) {
            if ((this.onBegingetNewsInfoDelegate == null)) {
                this.onBegingetNewsInfoDelegate = new BeginOperationDelegate(this.OnBegingetNewsInfo);
            }
            if ((this.onEndgetNewsInfoDelegate == null)) {
                this.onEndgetNewsInfoDelegate = new EndOperationDelegate(this.OnEndgetNewsInfo);
            }
            if ((this.ongetNewsInfoCompletedDelegate == null)) {
                this.ongetNewsInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetNewsInfoCompleted);
            }
            base.InvokeAsync(this.onBegingetNewsInfoDelegate, new object[] {
                        id}, this.onEndgetNewsInfoDelegate, this.ongetNewsInfoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override LateralMenus.GlobalManager.GlobalManagerPortType CreateChannel() {
            return new GlobalManagerPortTypeClientChannel(this);
        }
        
        private class GlobalManagerPortTypeClientChannel : ChannelBase<LateralMenus.GlobalManager.GlobalManagerPortType>, LateralMenus.GlobalManager.GlobalManagerPortType {
            
            public GlobalManagerPortTypeClientChannel(System.ServiceModel.ClientBase<LateralMenus.GlobalManager.GlobalManagerPortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetRate(LateralMenus.GlobalManager.getRateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getRate", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.GlobalManager.getRateResponse EndgetRate(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.GlobalManager.getRateResponse _result = ((LateralMenus.GlobalManager.getRateResponse)(base.EndInvoke("getRate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegincreateNewsComment(LateralMenus.GlobalManager.createNewsCommentRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("createNewsComment", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.GlobalManager.createNewsCommentResponse EndcreateNewsComment(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.GlobalManager.createNewsCommentResponse _result = ((LateralMenus.GlobalManager.createNewsCommentResponse)(base.EndInvoke("createNewsComment", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsumMarkNews(int id_article, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id_article;
                System.IAsyncResult _result = base.BeginInvoke("sumMarkNews", _args, callback, asyncState);
                return _result;
            }
            
            public int EndsumMarkNews(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("sumMarkNews", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetRateById(LateralMenus.GlobalManager.getRateByIdRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getRateById", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.GlobalManager.getRateByIdResponse EndgetRateById(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.GlobalManager.getRateByIdResponse _result = ((LateralMenus.GlobalManager.getRateByIdResponse)(base.EndInvoke("getRateById", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTest(LateralMenus.GlobalManager.TestRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Test", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.GlobalManager.TestResponse EndTest(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.GlobalManager.TestResponse _result = ((LateralMenus.GlobalManager.TestResponse)(base.EndInvoke("Test", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginrateNews(int id_user, int id_target, int mark, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = id_user;
                _args[1] = id_target;
                _args[2] = mark;
                System.IAsyncResult _result = base.BeginInvoke("rateNews", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndrateNews(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("rateNews", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsearchKeyword(LateralMenus.GlobalManager.searchKeywordRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("searchKeyword", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.GlobalManager.searchKeywordResponse EndsearchKeyword(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.GlobalManager.searchKeywordResponse _result = ((LateralMenus.GlobalManager.searchKeywordResponse)(base.EndInvoke("searchKeyword", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsearchNews(LateralMenus.GlobalManager.searchNewsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("searchNews", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.GlobalManager.searchNewsResponse EndsearchNews(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.GlobalManager.searchNewsResponse _result = ((LateralMenus.GlobalManager.searchNewsResponse)(base.EndInvoke("searchNews", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetNewsInfo(LateralMenus.GlobalManager.getNewsInfoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getNewsInfo", _args, callback, asyncState);
                return _result;
            }
            
            public LateralMenus.GlobalManager.getNewsInfoResponse EndgetNewsInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                LateralMenus.GlobalManager.getNewsInfoResponse _result = ((LateralMenus.GlobalManager.getNewsInfoResponse)(base.EndInvoke("getNewsInfo", _args, result)));
                return _result;
            }
        }
    }
}
